replicaCount: 1

image:
  repository: natalii571/textme-auth-service
  tag: latest

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

config:
  LOG_LEVEL: info
  JWT_ALGORITHM: HS256
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  JWT_REFRESH_TOKEN_EXPIRE_DAYS: "7"

secret:
  DATABASE_URL: postgresql+asyncpg://postgres:password@auth-postgres-chart:5432/authDB
  JWT_SECRET_KEY: SUPER_PUPER_SECRET


database:
  postgres:
    enabled: true
  mongo:
    enabled: false

postgres-chart:
  postgres:
    user: postgres
    password: password
    db: authDB

  persistence:
    accessMode: ReadWriteOnce
    storageClass: gp2
    size: 1Gi

migration:
  enabled: true


ingress:
  enabled: true
  paths:
    - path: /auth(/|$)(.*)
      pathType: ImplementationSpecific
      servicePort: 8000