replicaCount: 3

image:
  repository: natalii571/auth-service
  tag: latest

service:
  port: 8000
  targetPort: 8000

config:
  LOG_LEVEL: info
  JWT_ALGORITHM: HS256
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  JWT_REFRESH_TOKEN_EXPIRE_DAYS: "7"

secret:
  DATABASE_URL: postgresql+asyncpg://postgres:password@auth-postgres-chart:5432/authDB
  JWT_SECRET_KEY: SUPER_PUPER_SECRET


database:
  postgres:
    enabled: true
  mongo:
    enabled: false

migration:
  enabled: true


postgres-chart:
  postgres:
    user: postgres
    password: password
    db: authDB