replicaCount: 1

image:
  repository: natalii571/textme-chat-service
  tag: latest
  imagePullPolicy: Always

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

config:
  LOG_LEVEL: info
  JWT_ALGORITHM: HS256
  MONGO_DB: chatDB

secret:
  MONGO_URL: mongodb://root:password@chat-mongo-chart:27017/chatDB?authSource=admin
  JWT_SECRET_KEY: SUPER_PUPER_SECRET


database:
  postgres:
    enabled: false
  mongo:
    enabled: true

mongo-chart:
  secret:
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: password
    MONGO_INITDB_DATABASE: chatDB

  persistence:
    accessMode: ReadWriteOnce
    storageClass: gp2
    size: 1Gi


migration:
  enabled: false

ingress:
  enabled: true
  paths:
    - path: /chat(/|$)(.*)
      pathType: ImplementationSpecific
      servicePort: 8000