 {{- if .Values.minio.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "infra-chart.minio.fullname" . }}
spec:
  serviceName: {{ include "infra-chart.minio.fullname" . }}
  replicas: {{ .Values.minio.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "infra-chart.minio.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "infra-chart.minio.fullname" . }}
    spec:
      containers:
        - name: minio
          image: "{{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}"
          imagePullPolicy: {{ .Values.minio.image.pullPolicy }}
          args: ["server", "/data", "--console-address", ":9001"]
          ports:
            - containerPort: 9000
              name: api
            - containerPort: 9001
              name: console
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "infra-chart.minio.fullname" . }}-secret
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "infra-chart.minio.fullname" . }}-secret
                  key: MINIO_ROOT_PASSWORD
            - name: MINIO_DEFAULT_BUCKETS
              value: {{ .Values.minio.defaultBucket }}
          volumeMounts:
            - name: minio-storage
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: minio-storage
      spec:
        accessModes:
          - {{ .Values.minio.persistence.accessMode }}
        storageClassName: {{ .Values.minio.persistence.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.minio.persistence.size }}            {{- end }}
