 {{- if .Values.minio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "infra-chart.minio.fullname" . }}
spec:
  selector:
    app: {{ include "infra-chart.minio.fullname" . }}
  ports:
    - name: api
      port: {{ .Values.minio.service.port }}
      targetPort: 9000
    - name: console
      port: {{ .Values.minio.service.consolePort }}
      targetPort: 9001
  type: ClusterIP

   {{- end }}
