apiVersion: v1
kind: Service
metadata:
  name: {{ include "infra-chart.rabbitmq.fullname" . }}
spec:
  selector:
    app: {{ include "infra-chart.rabbitmq.fullname" . }}
  ports:
    - name: amqp
      port: {{ .Values.rabbitmq.service.port }}
      targetPort: 5672
    - name: management
      port: {{ .Values.rabbitmq.service.managementPort }}
      targetPort: 15672
  type: ClusterIP