apiVersion: v1
kind: Service
metadata:
  name: {{ include "infra-chart.redis.fullname" . }}
spec:
  selector:
    app: {{ include "infra-chart.redis.fullname" . }}
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: 6379
  type: ClusterIP