apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongo-chart.fullname" . }}-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongo.user | b64enc }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongo.password | b64enc }}
  MONGO_INITDB_DATABASE: {{ .Values.mongo.db | b64enc }}