"""add avatar url

Revision ID: 85a1a1aa7a75
Revises: f3b9098ed247
Create Date: 2026-05-06 13:45:29.459935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85a1a1aa7a75'
down_revision: Union[str, Sequence[str], None] = 'f3b9098ed247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('avatar_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'avatar_url')
    # ### end Alembic commands ###
