{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app-chart.fullname" . }}-migration
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Waiting for database..."
              until python -c "import socket; s=socket.socket(); s.settimeout(2); s.connect(('{{ .Release.Name }}-postgres-chart', 5432)); s.close()"; do
                echo "Database is not ready yet..."
                sleep 2
              done
              echo "Database is ready"
              uv run alembic upgrade head
          env:
            - name: DATABASE_URL
              value: {{ .Values.secret.DATABASE_URL | quote }}
            - name: JWT_SECRET_KEY
              value: {{ .Values.secret.JWT_SECRET_KEY | quote }}
            - name: JWT_ALGORITHM
              value: {{ .Values.config.JWT_ALGORITHM | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.config.LOG_LEVEL | quote }}
{{- end }}