apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-chart.fullname" . }}-secret
type: Opaque
stringData:
  {{- range $key, $val := .Values.secret }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}