apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-chart.fullname" . }}-secret
type: Opaque
stringData:
  {{- if ((.Values.database).postgres).enabled }}
  DATABASE_URL: {{ .Values.database.postgres.url | quote }}
  {{- end }}
  {{- if ((.Values.database).mongo).enabled }}
  MONGO_URL: {{ .Values.database.mongo.url | quote }}
  {{- end }}
  {{- range $key, $val := .Values.secret }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}